
import core.const

HASH_TEST_FILE_PREFIX = 'big'
HASH_TEST_FILE_SUFFIX = '.txt'
HASH_TEST_BASE_FILE_SIZE = 1024 * 1024
HASH_TEST_FILE_MIN = 1
HASH_TEST_FILE_MAX = core.const.MAX_HASH_PERF_VALUES + 10

X_FOLDER = 'x'
Y_FOLDER = 'y'